# netlify.toml (at your project root)

[build]
  publish = "Index"
  command = ""  # if you have a build step, put it here

[[redirects]]
  from = "/cloud/*"
  to = "/main.html"
  status = 302
  force = true
  conditions = { Role = ["guest"] }

# (You can add any other redirects or headers below.)
